# Generated by Django 3.1.5 on 2021-01-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
            ],
        ),
    ]
